apiVersion: v1
kind: Service
metadata:
  name: master
  namespace: rabbitmq
spec:
  selector:
    app_name: master
  ports:
  - name: master-tcp
    port: 5672
    protocol: TCP
  - name: master-web-ui
    port: 15672
    protocol: TCP

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: master
  namespace: rabbitmq
  labels:
    app_name: master
spec:
  replicas: 1
  selector:
    app_name: master
  template:
    metadata:
      labels:
        app_name: master
    spec:
      hostname: rabbitmq
      containers:
      - name: master
        image: rabbitmq:3.5.2-management
        ports:
        - containerPort: 5672
          name: mast-tcp-loc
          protocol: TCP
        - containerPort: 15672
          name: mast-web-ui-loc
          protocol: TCP
        env:
        - name: RABBITMQ_NODE_NAME
          value: "rabbitmq"
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-data
      volumes:
      - name: rabbitmq-data
        awsElasticBlockStore:
          volumeID: <insert_your_volumeID>
          fsType: ext4
